### ISSUE TITLE
Currency Drop Down Menu Bug

### ISSUE THREAD

**Issue by 0x1Luffy** [catherineisonline/shopping-time#1]
when we initially click on change currency icon, then a drop-down menu appears, again when clicked on any of the navbar item eg: shoes then the drop-down menu stays it should hide.

Uploading Untitled video - Made with Clipchamp (1).mp4…

**Comment by catherineisonline** [comment]
> when we initially click on change currency icon, then a drop-down menu appears, again when clicked on any of the navbar item eg: shoes then the drop-down menu stays it should hide.
> 
> Uploading Untitled video - Made with Clipchamp (1).mp4…

Hi, thanks for reporting this issue! I will get back to this project very soon 😍

**Comment by catherineisonline** [comment]
The issue has been fixed
