### ISSUE TITLE
Shipping Address in Order.js

### ISSUE THREAD

**Issue by srhn19** [catherineisonline/shopping-time#8]
Hi, the address and province won't display in the Order summary. In the _Order.js_ file's Shipping Address list element,

- _orderFormValue.address_ can be renamed to _orderFormValue.streetaddress_.
- _orderFormValue.province_ can be added.

Kind regards.

**Comment by catherineisonline** [comment]
@srhn19 I don't know why I skipped this issue or missed the notification however the issue is solved, thanks for the feedback!
